/** Lista de artistas (ordem alfabética) para seleção em demandas e relatórios. */
export const ARTISTS = [
  "Andrezin O Principe",
  "Anna Maya",
  "Arasta Pra Riba",
  "Betinflix",
  "Bia Cavalcante",
  "Bonde Do Perreira",
  "Bota Na Pressão",
  "Boy Do Médio",
  "Br Brown",
  "Caddu Ds",
  "Carla Alessandra",
  "Ciindy Moura",
  "Cleber e Gusttavo",
  "Daniel Silva",
  "Dany Façanha",
  "Danilo Pegada",
  "Davi Alenncar",
  "Davi Nascimento",
  "David MM",
  "Demoro",
  "Diney e Rafael",
  "Dj Vicente",
  "Edu Mello",
  "Edilson San",
  "Ellen Nery",
  "Felipe Ennzo",
  "Filipe Vieira",
  "Gabriel Alongado",
  "Guilherme Andrade",
  "Guilherme Love",
  "Gusta Brandão",
  "Hendison Trankinha",
  "Icaro Miranda",
  "Jack Pallas",
  "Jaki Coutinho",
  "Japa Vaqueiro",
  "Jennifer K",
  "João Lucas Hendson",
  "Jonas Cantor",
  "Jota",
  "Jully Beatriz",
  "Juninho Ousado",
  "Kaiuzin",
  "Karine Medeiros",
  "Korea",
  "Larrysa Alencar",
  "Los Pankas",
  "Lucas Maia",
  "Mari Reis",
  "Marissa Helen",
  "Mauricio Dallas",
  "MC Nova Era",
  "Mickaelly",
  "Mistura",
  "Nanda Batista",
  "Pamela Lima",
  "Patrick leão",
  "Placilio Diniz",
  "Rodrigo Keven",
  "Ruan Douglas",
  "Sanchez",
  "Tales Pires",
  "Thiaguinho Mala Mansa",
  "Tuca no Beat",
  "Uyvens",
  "Véi da Pressão",
  "Victor Sanfoneiro",
  "Vitinho Do Brega",
  "Vitor Daslent's",
  "Wyllifi Vaqueiro",
  "Xvctor",
  "Zeca Agricultor",
] as const;

export type ArtistName = (typeof ARTISTS)[number];
