/** Lista de artistas (ordem alfabética) para seleção em demandas e relatórios. */
export const ARTISTS = [
  "LOCAÇÃO DE STUDIO",
  "MIX | MASTER EXTERNO",
  "PRODUÇÃO EXTERNA",
  "Anna Maya",
  "Andrezinho Melo",
  "Arasta Pra Riba",
  "Bonde Do Perreira",
  "Bota Na Pressão",
  "Br Brown",
  "Cheber e João",
  "Dany Façanha",
  "Danilo Pegada",
  "Davi Alenncar",
  "David MM",
  "Demoro",
  "DJ Triston",
  "Dj Vicente",
  "Edu Mello",
  "Edilson San",
  "Felipe Ennzo",
  "Felipe M1X",
  "Filipe Vieira",
  "Guilherme Andrade",
  "Guus",
  "Gusta Brandão",
  "Hendison Trankinha",
  "Hill do Piseiro",
  "Icaro Miranda",
  "Jennifer K",
  "Jesse Nery",
  "João Lucas Hendson",
  "Jonas Cantor",
  "Jota",
  "Jully Beatriz",
  "Juninho Ousado",
  "Kaisanzz",
  "Kaiuzin",
  "Karine Medeiros",
  "Korea",
  "Larrysa Alencar",
  "Los Pankas",
  "Lucas Maia",
  "Mareza",
  "Marissa Helen",
  "MC Nova Era",
  "Mhad",
  "Mickaelly",
  "Mistura",
  "Na Faixa Music",
  "Paulinha Rewett",
  "Playzinho 081",
  "Sanchez",
  "Sterzinha",
  "Sub Zero",
  "Tales Pires",
  "Thiaguinho Mala Mansa",
  "Tuca no Beat",
  "Uyvens",
  "Véi da Pressão",
  "Victor Sanfoneiro",
  "Vitinho Do Brega",
  "Vitor Daslent's",
  "Wyllifi Vaqueiro",
  "Zeca Agricultor",
] as const;

export type ArtistName = (typeof ARTISTS)[number];
